# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7b67d2cd7c19f205c76bce05fb6a40ae0bbc7f839c6cb0e44bd87c5b0ee4b1833042e4e58356b3f6203772b0e063912058d12839d4770afee507798763ac600d

test:
  secret_key_base: 7a17415dfeea125de652858d183174fdad22890c7b02f091b5630aacf631ee0529817ebac493a9cea2ca70ad1ed9eeb235da70c2d28cced59ca9fcacca3fc364

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
